language: java

jdk:
  - openjdk15

sudo: false

script:
  - mvn test -B

env:
  global:
    - CODECOV_TOKEN="88b8da9f-e19d-4a1a-bfe8-461b689647ff"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -bogdankopylov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always